title: Patchwork platformer
hero_image: images/banner.png
description: Create a collaborative game
pdf: false
steps:
  - title: What you will make
  - title: Create your level
  - title: Share your level


